# Maria — FAQ simples e vendedor.
# Responde gatilho → resposta curta (sempre carimbada com " (faq.yaml)").

categories:

  greet:
    triggers: ["oi","olá","ola","bom dia","boa tarde","boa noite"]
    answers:
      - "Oi! Pra eu te orientar certinho, seu cabelo é **liso**, **ondulado**, **cacheado** ou **crespo**? (faq.yaml)"

  hair_type:
    triggers: ["liso","ondulado","cacheado","crespo"]
    answers:
      - "Show! E qual teu principal incômodo hoje: **frizz**, **falta de brilho** ou **difícil de alinhar**? (faq.yaml)"

  hair_pain:
    triggers:
      - "frizz"
      - "falta de brilho"
      - "difícil de alinhar"
      - "dificil de alinhar"
      - "alinhamento"
      - "volume"
    answers:
      - "Perfeito! A *Progressiva Vegetal* é **sem formol**, hidrata e alinha os fios — já são **40 mil+ vendas** no Brasil. (faq.yaml)"

  price:
    triggers: ["preço","preco","quanto custa","valor","tem promoção","tem promocao","preço por favor"]
    answers:
      - "O preço original é **R$ 197**, mas hoje sai por **R$ 150** 🔥 E o melhor: **você só paga quando recebe** (garantia total). (faq.yaml)"

  payment:
    triggers: ["como paga","formas de pagamento","aceita cartão","aceita cartao","pix","parcelado","12x"]
    answers:
      - "Na entrega você escolhe: **dinheiro**, **Pix**, ou **cartão em até 12x** (juros do cartão). (faq.yaml)"

  delivery:
    triggers: ["entrega","quando chega","prazo","demora","prazo de entrega","chega quando"]
    answers:
      - "Entrega rápida: **até 24h nas capitais** e **até 72 horas nas demais localidades**. (faq.yaml)"

  safety:
    triggers: ["formol","faz mal","alergia","tenho alergia","contra indicacao","contra-indicação","contra indicacão"]
    answers:
      - "Pode ficar tranquila: é **livre de formol adicionado**. Recomendamos **teste de mecha** se o couro cabeludo for sensível. (faq.yaml)"

  how_to_use:
    triggers: ["como usa","como aplicar","como funciona","aplicacao","aplicação","modo de uso"]
    answers:
      - "Passo rápido: lave, **aplique e deixe agir ~40 min**, enxágue e finalize; com escova/chapinha o alinhamento dura mais. (faq.yaml)"

  offer_push:
    triggers: ["quero","fechar","comprar","link","manda o link","fechamos"]
    answers:
      - "Fechamos por **R$ 150** com pagamento só na entrega? Posso adiantar seu pedido agora. (faq.yaml)"

  checkout_collect:
    triggers: ["dados","finalizar","fechamento","fazer pedido","agendar entrega","quero fechar"]
    answers:
      - "Perfeito! Me confirma rapidinho: **Nome completo**, **Telefone com DDD**, **CEP, número e complemento**, e o **melhor dia** pra receber. (faq.yaml)"

  doubts_generic:
    triggers: ["funciona mesmo","é bom","vale a pena","funciona de verdade"]
    answers:
      - "Funciona sim 💚 Alinha, reduz frizz e dá brilho — e já são **40 mil+ clientes** satisfeitas. (faq.yaml)"

  thanks:
    triggers: ["obrigado","obrigada","valeu"]
    answers:
      - "Eu que agradeço! Qualquer coisa, tô por aqui 💛 (faq.yaml)"
