bot_id: maria
persona_name: "Maria"
language: "pt-BR"

product:
  name: "Progressiva X"
  price_original: 197
  price_target: 150             # <- ajuste p/ oferta matadora
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"  # ou o seu
  site_url: "https://tpofertas.com/collections/cod-todos"
  coupon_code: "TOP-AGO2025-PROGRVG-150"
  coupon_post_payment_only: true
  delivery_sla:
    capitals_hours: 24          # <- 24h capitais
    others_hours: 72            # <- até 72h demais
  how_to_use: >
    Lave os cabelos, aplique o produto e deixe agir por ~40 minutos.
    Para maior durabilidade, finalize com escova/chapinha.
  value_props:
    - "reduz *frizz* sem pesar"
    - "deixa *alinhado com brilho* já na primeira aplicação"
    - "aplicação simples em casa, com passo a passo"

marketing:
  sold_count: 40000             # <- reforço social

media:
  opening_photo_url: "https://cdn.shopify.com/s/files/1/0947/7609/9133/files/Inserirumtitulo_8.png?v=1755836200"
                               # <- mantém sua foto
flags:
  flow_only: true              # <- Maria responde só via FAQ.yaml (simples, previsível)
  disable_hooks_fallback: true # <- desliga hooks pra evitar rajadas
  has_cod: true
  send_opening_photo: true     # <- garante a foto de abertura 1x
  guardrails_strict: true
  allow_audio_in: true
  allow_audio_out: false
  small_talk_soften: true

messages:
  opening:
    - "Oi! Pra eu te orientar certinho, seu cabelo é **liso**, **ondulado**, **cacheado** ou **crespo**?"
  # opcional manter opening_named; o core só usará se já houver nome:
  opening_named:
    - "Oi, {{ profile.name }}! Pra eu te orientar certinho, seu cabelo é **liso**, **ondulado**, **cacheado** ou **crespo**?"
  cod_short: "Pagamento na entrega (COD)."
  delivery_info:
    - "Prazo: até {{product.delivery_sla.capitals_hours}}h capitais e até {{product.delivery_sla.others_hours}}h demais regiões."
  payment_info:
    - "{{messages.cod_short}} Você confirma o pedido e paga quando receber — simples e seguro."

guardrails:
  price_min: 149
  price_max: 249
  allow_links_only_from_list: true
  allowed_links:
    - "{{product.checkout_link}}"
    - "{{product.site_url}}"
  freeze_fields:
    - "price_target"
    - "checkout_link"
    - "coupon_code"
    - "sold_count"
