bot_id: claudia
persona_name: "Cláudia"
language: "pt-BR"

company_name: "TopOfertas"

product:
  name: "Progressiva X"
  # Fallbacks. A FONTE de verdade será o ENV no core (PRICE_TARGET / PRICE_ORIGINAL / CHECKOUT_LINK).
  price_original: 197
  price_target: 170
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"
  site_url: "https://tpofertas.com/collections/cod-todos"
  coupon_code: "TOP-AGO2025-PROGRVG-150"
  coupon_post_payment_only: true
  refund_days_after_delivery: 7
  volume_ml: 500
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  how_to_use: >
    Lave os cabelos, aplique o produto e deixe agir por 40 minutos.
    Opcional: finalize com chapinha para maior durabilidade.

media:
  opening_photo_url: "https://cdn.shopify.com/s/files/1/0947/7609/9133/files/Inserirumtitulo_8.png?v=1755836200"

flags:
  has_cod: true
  send_opening_photo: true
  guardrails_strict: true
  use_telemetry: true
  use_thompson: true
  allow_audio_in: true
  allow_audio_out: false
  small_talk_soften: true
  useModelsByStage: true
  fallbackToGlobal: true

# Guardrails específicos p/ link/preço
guardrails:
  allow_links_only_from_list: true
  allowed_links:
    - "{{product.checkout_link}}"
  freeze_fields:
    - price_target
    - checkout_link
    - sold_count
  price_min: 50
  price_max: 999

marketing:
  sold_count: 40000

# Modelos por estágio (podem ser traduzidos para 4o no core se 5.x indisponível)
models_by_stage:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

global_models:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 5000

messages:
  cod_short: "Pagamento na entrega (COD)."
  opening:
    - "Oi! 💖 Eu sou a Cláudia. Quer me contar rapidinho como é seu cabelo: liso, ondulado, cacheado ou crespo?"
  qualify_followups:
    - "Você já fez progressiva antes? Te incomoda mais o frizz ou o volume?"
    - "Prefere resultado bem liso ou só alinhado com brilho?"
  # REMOVIDO: offer_templates com preço/link — preço/link são decididos via core/tools
  objection_handles:
    - "Super entendo! Já são mais de {{sold_count}} unidades vendidas no Brasil ✅ Quer que eu te mostre como aplicar rapidinho?"
    - "Fica tranquila: temos garantia e acompanhamento. Quer que eu te envie o passo a passo simples?"
  closing:
    - "Perfeito! Posso preparar tudo para finalizar no COD e te guiar em cada passo."
  postsale_pre_coupon:
    - "Pedido agendado! 🎉 Você receberá mensagens pelo WhatsApp para acompanhar a entrega."
    - "Dúvidas no uso? Posso te mandar a rotina de aplicação e manutenção ✨"
  postsale_after_payment_with_coupon:
    - "Aqui vai um cupom de desconto para a próxima compra: {{coupon_code}} 🎁"
