# configs/bots/claudia/settings.yaml
bot_id: claudia
persona_name: "Cláudia"
language: "pt-BR"

product:
  name: "Progressiva Vegetal"
  store_name: "TopOfertas"
  price_original: 197
  price_target: 170
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"
  site_url: "https://tpofertas.com/collections/cod-todos"
  coupon_code: "TOP-AGO2025-PROGRVG-150"
  coupon_post_payment_only: true
  refund_days_after_delivery: 7
  volume_ml: 500
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  how_to_use: >
    Lave os cabelos, aplique o produto e deixe agir por 40 minutos.
    Para maior durabilidade, finalize com escova/chapinha.
  upsell_flatiron:
    enabled: true
    pitch: "Se quiser, te indico uma chapinha com ótimo custo-benefício para potencializar o efeito."
  opening_hours: "06h às 21h (escala variável)"

media:
  # A foto é enviada automaticamente pelo flow/index.js quando flags.send_opening_photo=true
  opening_photo_url: "https://cdn.shopify.com/s/files/1/0947/7609/9133/files/Inserirumtitulo_8.png?v=1755836200"

messages:
  # Usadas pelo greet.js (variante genérica)
  opening:
    - "Oi! Eu sou a Cláudia da *{{ product.store_name }}*. Pra te orientar certinho: seu cabelo é **liso**, **ondulado**, **cacheado** ou **crespo**?"
  # Usadas pelo greet.js quando já conhecemos o nome e/ou parte do perfil
  opening_named:
    - "Oi, {{ profile.name }}! Pra te orientar certinho: seu cabelo é **liso**, **ondulado**, **cacheado** ou **crespo**?"
  # Hints usados no FAQ (aplicações e duração)
  applications_hint: "2–4 aplicações (varia com comprimento)"
  duration_hint: "de 2 a 3 meses"

marketing:
  sold_count: 40000

promotions:
  raffle:
    enabled: false
    teaser: "Comprando este mês você participa do nosso sorteio de prêmios. Quer que eu te explique rapidinho?"

flags:
  has_cod: true
  # Janela de dedupe persistente (entre invocações). Pode ajustar para 60000 (60s), 90000 (90s) etc.
  reply_dedupe_ms: 120000   # 120s
  send_opening_photo: true
  disable_opening_hook: true
  guardrails_strict: true
  use_telemetry: true
  use_thompson: true
  allow_audio_in: true
  allow_audio_out: false
  small_talk_soften: true
  useModelsByStage: true
  fallbackToGlobal: true
  debug_log_router: false

# Modelos por estágio (opcional; o core usa se flags.useModelsByStage=true)
models_by_stage:
  recepcao: "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta: "gpt-5-mini"
  objecoes: "gpt-5"
  fechamento: "gpt-5"
  posvenda: "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 5000

# Guardrails: libera explicitamente os links do settings (checkout + site)
guardrails:
  allowed_links:
    - "{{ product.checkout_link }}"
    - "{{ product.site_url }}"
