# configs/bots/claudia/settings.yaml
bot_id: claudia
persona_name: "Cláudia"
language: "pt-BR"

product:
  name: "Progressiva Vegetal"
  store_name: "TopOfertas"
  price_original: 197
  price_target: 170
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"
  site_url: "https://tpofertas.com/collections/cod-todos"
  coupon_code: "TOP-AGO2025-PROGRVG-150"
  coupon_post_payment_only: true
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  how_to_use: >
    Lave os cabelos, aplique o produto e deixe agir por 40 minutos. Para maior durabilidade, finalize com escova/chapinha.
  upsell_flatiron:
    enabled: true
    pitch: "Se quiser, te indico uma chapinha com ótimo custo-benefício para potencializar o efeito."
  opening_hours: "06h às 21h (escala variável)"

media:
  opening_photo_url: "https://cdn.shopify.com/s/files/1/0947/7609/9133/files/Inserirumtitulo_8.png?v=1755836200"

flags:
  has_cod: true
  send_opening_photo: true
  guardrails_strict: true
  use_telemetry: true
  use_thompson: true
  allow_audio_in: true
  allow_audio_out: false
  small_talk_soften: true
  useModelsByStage: true
  fallbackToGlobal: true

marketing:
  sold_count: 40000

models_by_stage:
  recepcao: "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta: "gpt-5-mini"
  objecoes: "gpt-5"
  fechamento: "gpt-5"
  posvenda: "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 5000

# >>> NOVO: guardrails libera explicitamente os links do settings (checkout + site)
guardrails:
  allowed_links:
    - "{{ product.checkout_link }}"
    - "{{ product.site_url }}"
