bot_id: claudia
persona_name: "Cláudia"
language: "pt-BR"

product:
  name: "Progressiva X"
  price_original: 197
  price_target: 170
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"
  site_url: "https://tpofertas.com/collections/cod-todos"
  coupon_code: "TOP-AGO2025-PROGRVG-150"
  coupon_post_payment_only: true
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  how_to_use: >
    Lave os cabelos, aplique o produto e deixe agir por 40 minutos.
    Opcional para maior durabilidade: finalize com chapinha.

media:
  opening_photo_url: "https://cdn.shopify.com/s/files/1/0947/7609/9133/files/Inserirumtitulo_8.png?v=1755836200"

flags:
  has_cod: true
  send_opening_photo: true        # envia 1x a foto de abertura (se configurado no index)
  guardrails_strict: true         # trava preço/link/cupom
  allow_audio_in: true            # aceita áudio (se ASR habilitado)
  allow_audio_out: false
  small_talk_soften: true
  useModelsByStage: true
  fallbackToGlobal: true

# Modelos por etapa (mínimo necessário)
models_by_stage:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

# Opcional: fallback global (igual aos principais)
global_models:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 5000

messages:
  opening:
    - "Oi! Eu sou a Cláudia 😊 Como é seu cabelo: liso, ondulado, cacheado ou crespo?"
  qualify_followups:
    - "Você já fez progressiva antes? Te incomoda mais o frizz ou o volume?"
    - "Prefere resultado bem liso ou só alinhado com brilho?"
  offer_templates:
    - "Com base no que você me falou, recomendo o kit por R${{price_target}} 🛒 Posso te passar o link do checkout agora?"
    - "Fechando hoje, consigo manter por R${{price_target}}. Te mando o link seguro do checkout?"
  objection_handles:
    - "Entendo! Já são mais de {{sold_count}} unidades vendidas no Brasil ✅ No site você confere depoimentos e modo de uso. Quer um resumo aqui?"
    - "Fica tranquila: temos garantia e acompanhamento. Prefere que eu explique rapidinho o passo a passo?"
  closing:
    - "Perfeito! Te envio o link do checkout agora. Pagamento na entrega (COD). Você receberá mensagens pelo WhatsApp para acompanhar. Qualquer imprevisto, avise o entregador 💚"
  postsale_pre_coupon:
    - "Pagamento confirmado! 🎉 Você receberá mensagens para acompanhar a entrega. Dúvidas no uso? Posso te mandar a rotina ✨"
  postsale_after_payment_with_coupon:
    - "Como agradecimento, aqui vai um cupom para a PRÓXIMA compra: {{coupon_code}} 🎁"
  postsale_followup_days: 7
  features_intro:
    - "Claro! Te passo o modo de uso resumido:"
  delivery_info:
    - "Prazo: até {{delivery_sla.capitals_hours}}h capitais e até {{delivery_sla.others_hours}}h demais regiões."
  payment_info:
    - "Pagamento na entrega (COD). O link que envio é para confirmar o pedido e acompanhar pelo WhatsApp 🙂"

# Guardrails essenciais para 1 produto + links permitidos
guardrails:
  price_min: 149
  price_max: 249
  allow_links_only_from_list: true
  allowed_links:
    - "{{checkout_link}}"
    - "{{site_url}}"
  freeze_fields:
    - "price_target"
    - "checkout_link"
    - "coupon_code"
    - "sold_count"

# (Opcional) Contador de prova social
marketing:
  sold_count: 40000
