# configs/bots/claudia/settings.yaml — COMPLETÃO (polido p/ Cláudia)

bot_id: claudia
persona_name: "Cláudia"
language: "pt-BR"

product:
  name: "Progressiva Vegetal"        # nome correto fixo
  price_original: 197
  price_target: 170                  # pode ser sobrescrito por PRICE_TARGET (ENV)
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"  # CHECKOUT_LINK (ENV) sobrescreve
  site_url: "https://tpofertas.com/collections/cod-todos"
  coupon_code: "TOP-AGO2025-PROGRVG-150"   # COUPON_CODE (ENV) sobrescreve
  coupon_post_payment_only: true
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  how_to_use: >
    Lave os cabelos, aplique o produto e deixe agir por ~40 minutos.
    Para maior durabilidade, finalize com escova/chapinha.
  value_props:
    - "reduz *frizz* sem pesar"
    - "deixa *alinhado com brilho* já na primeira aplicação"
    - "aplicação simples em casa, com passo a passo"
  safety:
    claims:
      - "sem formol adicionado"
      - "sugerimos teste de mecha para couro cabeludo sensível"

media:
  opening_photo_url: "https://cdn.shopify.com/s/files/1/0947/7609/9133/files/Inserirumtitulo_8.png?v=1755836200"

flags:
  has_cod: true
  send_opening_photo: true         # envia 1x a foto de abertura
  guardrails_strict: true          # trava preço/link/cupom
  allow_audio_in: true             # aceita áudio (se ASR habilitado no core/env)
  allow_audio_out: false
  small_talk_soften: true
  useModelsByStage: true
  fallbackToGlobal: true

models_by_stage:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

global_models:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 5000

marketing:
  sold_count: 40000

messages:
  # Tom curto/alegre + pergunta final; sem mandar depoimentos no WhatsApp.
  opening:
    - "Oi! Eu sou a Cláudia 💛 Seu cabelo é liso, ondulado, cacheado ou crespo?"
  qualify_followups:
    - "Você já fez progressiva antes? Te incomoda mais o *frizz* ou o *volume*?"
    - "Você busca *bem liso* ou só *alinhado com brilho*?"
  cod_short: "Pagamento na entrega (COD) — você só paga quando receber."
  guarantee_short: "Garantia de 7 dias após a entrega."
  checkout_explain: >
    O link serve para você confirmar o endereço de entrega. Depois de preenchido,
    o entregador entra em contato para combinar a entrega com você.
  cep_fallback: >
    Se o seu CEP aparecer como não atendido, tente um CEP de trabalho ou de um(a) amigo(a).
    Estamos ampliando a rede de entrega e em breve cobriremos mais regiões. Posso te ajudar com isso?

  offer_templates:
    - "Hoje sai de R${{price_original}} por *R${{price_target}}*. {{messages.cod_short}} {{messages.guarantee_short}} Prefere tirar alguma dúvida agora ou já quer o link do checkout?"
    - "Consigo manter *R${{price_target}}* hoje. {{messages.cod_short}} {{messages.guarantee_short}} Quer que eu te envie o link para confirmar o endereço?"

  objection_handles:
    - "Fica tranquila: são mais de {{sold_count}} clientes no Brasil. Posso te resumir o modo de uso agora ou prefere já ir para o checkout?"
    - "Sem formol adicionado e aplicação simples. Prefere que eu explique rapidinho o passo a passo ou já quer o link?"

  closing:
    - "Perfeito! Vou te enviar o link seguro para confirmar o endereço. {{messages.checkout_explain}} Tudo certo assim?"
  closing_link_after:
    - "Link de checkout: {{product.checkout_link}}\nSe não abrir, copie e cole no navegador.\nQuando finalizar, me confirma aqui? 😊"

  postsale_pre_coupon:
    - "Pedido confirmado 🎉 Você receberá as atualizações da entrega. Se pintar alguma dúvida no uso, me chama!"
  postsale_after_payment_with_coupon:
    - "Como cliente especial, aqui vai um cupom de fidelidade para a PRÓXIMA compra: {{coupon_code}} 🎁"

guardrails:
  price_min: 149
  price_max: 249
  allow_links_only_from_list: true
  allowed_links:
    - "{{product.checkout_link}}"
    - "{{product.site_url}}"
  freeze_fields:
    - "price_target"
    - "checkout_link"
    - "coupon_code"
    - "sold_count"
 
faq:
  categories:
    delivery:
      triggers:
        - "\\b(prazo|entrega|quando\\s*(chega|recebo)|quanto\\s*tempo|frete)\\b"
      answers:
        - "Prazo típico: até {{product.delivery_sla.capitals_hours}}h em capitais e até {{product.delivery_sla.others_hours}}h nas demais regiões."
    payment:
      triggers:
        - "\\b(pagamento|pagar|forma(s)?\\s*de\\s*pagamento|pix|cartao|cartão|boleto|cod)\\b"
      answers:
        - "{{messages.cod_short}}"
    guarantee:
      triggers:
        - "\\b(garantia|devolu(c|ç)ao|troca|suporte)\\b"
      answers:
        - "{{messages.guarantee_short}}"
    usage:
      triggers:
        - "\\b(como\\s*usar|modo\\s*de\\s*uso|aplic(a|ação)|passo\\s*a\\s*passo|tempo\\s*de\\s*pausa)\\b"
      answers:
        - "{{product.how_to_use}}"
    cep_error:
      triggers:
        - "\\b(cep\\s*(invalido|inválido)|nao\\s*entrega|não\\s*entrega|cep\\s*nao\\s*atendido|cep\\s*não\\s*atendido)\\b"
      answers:
        - "{{messages.cep_fallback}}"
