bot_id: claudia
persona_name: "Cláudia"
language: "pt-BR"

company:
  name: "TopOfertas"
  hours: "06:00–21:00"

product:
  name: "Progressiva X"
  volume_ml: 500
  price_original: 197
  price_target: 170
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"
  site_url: "https://tpofertas.com/collections/cod-todos"
  coupon_code: "TOP-AGO2025-PROGRVG-150"
  coupon_post_payment_only: true
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  how_to_use: >
    Lave os cabelos, aplique e deixe agir 40 min.
    Para maior durabilidade, finalize com prancha.

media:
  opening_photo_url: "https://cdn.shopify.com/s/files/1/0947/7609/9133/files/Inserirumtitulo_8.png?v=1755836200"

flags:
  has_cod: true
  send_opening_photo: true
  guardrails_strict: true
  use_telemetry: true
  use_thompson: true
  allow_audio_in: true
  allow_audio_out: false
  small_talk_soften: true
  useModelsByStage: true
  fallbackToGlobal: true

marketing:
  sold_count: 40000

models_by_stage:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

global_models:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 5000

messages:
  opening:
    - "Oi! 💖 Eu sou a Cláudia. Me conta rapidinho como é seu cabelo (liso, ondulado, cacheado ou crespo)?"
  qualify_followups:
    - "Você já fez progressiva antes?"
    - "Prefere resultado bem liso ou só alinhado?"
  offer_templates:
    - "Com base no que me falou, recomendo por **R${{price_target}}** 🛒 Posso te mandar o link do checkout?"
  objection_handles:
    - "Super entendo! Já são mais de {{sold_count}} unidades vendidas ✅. Quer que eu resuma o modo de uso?"
  closing:
    - "Perfeito! Te envio o link seguro do checkout. Pagamento na entrega (COD)."
