# configs/bots/claudia/settings.yaml
bot_id: claudia

company:
  name: "TopOfertas"
  hours: "06:00–21:00"

flags:
  flow_only: true
  debug_trace_replies: true         # carimbo (flow/...)
  has_cod: true
  force_funnel: true
  useModelsByStage: true
  fallbackToGlobal: true
  send_opening_photo: true          # <- garante a foto no primeiro contato

product:
  name: "Progressiva Vegetal"
  price_original: 197
  price_target: 170
  applications_up_to: 10
  duration_avg: "de 2 a 3 meses"
  volume_ml: 500
  site_url: "https://seusite.com"
  checkout_link: "https://seusite.com/checkout"
  refund_days_after_delivery: 7
  how_to_use: >
    Lave os cabelos, seque ~80%, aplique mecha a mecha, pause 40–50min,
    enxágue, escove e pranche.
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  coupon_post_payment_only: false
  coupon_code: ""

media:
  opening_photo_url: "https://cdn.seusite.com/arte-abertura.jpg"

guardrails:
  allow_links_only_from_list: true
  allowed_links:
    - "{{site_url}}"
    - "{{checkout_link}}"
  price_min: 100
  price_max: 300
  freeze_fields:
    - "price_target"
    - "checkout_link"
    - "coupon_code"

# Mensagens para o greet (AB test)
abtest:
  greet:
    enabled: true
    weights:
      A: 1
      B: 1

messages:
  # Variante A: profissional/credibilidade
  opening_A:
    - "Oi, eu sou a Cláudia da *TopOfertas* ✨ especialista na Progressiva Vegetal. Qual o seu nome? Posso te explicar como funciona o tratamento?"
  # Variante B: leve/acolhedora
  opening_B:
    - "Oi! Eu sou a Cláudia, prazer falar com você 😊 Como posso te chamar? Quer que eu te explique rapidinho sobre a Progressiva Vegetal?"

  delivery_info:
    - "Entregamos rápido: **{{delivery_sla.capitals_hours}}h** capitais / **{{delivery_sla.others_hours}}h** demais locais."
  features_intro:
    - "Como usar (resumo):"

# Modelos por etapa (compat 5.x↔4.x pelo core)
models_by_stage:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

global_models:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 4000

audio:
  asr_provider: "openai"
  asr_model: "whisper-1"
  tts_provider: "none"
  tts_voice: "alloy"
