# configs/bots/claudia/settings.yaml
bot_id: claudia

company:
  name: "TopOfertas"
  hours: "06:00–21:00"

# Flags operacionais (usados pelos flows)
flags:
  flow_only: true
  debug_trace_replies: true          # carimbo (flow/...)
  has_cod: true
  force_funnel: true
  useModelsByStage: true
  fallbackToGlobal: true
  send_opening_photo: true           # envia a foto no primeiro contato
  small_talk_soften: true
  guardrails_strict: true

# Produto (dados usados nos textos e guardrails)
product:
  name: "Progressiva Vegetal"
  price_original: 197
  price_target: 170
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"
  site_url: "https://tpofertas.com/collections/cod-todos"
  anvisa_ok: true
  how_to_use: >
    Lave os cabelos, seque ~80%, aplique mecha a mecha e deixe agir 40–50 min.
    Enxágue, escove e pranche para melhor selagem. Rende em média 3 meses.
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  coupon_post_payment_only: false
  coupon_code: ""

# Mídia usada no microprocesso de abertura
media:
  opening_photo_url: "https://cdn.shopify.com/s/files/1/0947/7609/9133/files/Inserirumtitulo_8.png?v=1755836200"

marketing:
  sold_count: 40000

# Modelos por etapa — pode usar gpt-5-* (o core traduz p/ compat se preciso)
models_by_stage:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

# Fallbacks globais (mantém compat)
global_models:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 4000

audio:
  asr_provider: "openai"
  asr_model: "whisper-1"
  tts_provider: "none"
  tts_voice: "alloy"

# Guardrails (não deixar o bot alterar preço/link)
guardrails:
  allow_links_only_from_list: true
  allowed_links:
    - "{{checkout_link}}"
    - "{{site_url}}"
  price_min: 149
  price_max: 249
  freeze_fields:
    - "price_target"
    - "checkout_link"
    - "sold_count"

messages:
  # textos prontos que outros flows podem reutilizar
  opening:
    - "Oi! Eu sou a Cláudia. Consigo te orientar certinho. Me diz rapidinho o tipo do seu cabelo (liso, ondulado, cacheado ou crespo)?"
    - "Oi! Sou a Cláudia. Pra te ajudar melhor: seu cabelo é liso, ondulado, cacheado ou crespo?"
  delivery_info:
    - "Prazo de entrega: até {{delivery_sla.capitals_hours}}h capitais e até {{delivery_sla.others_hours}}h demais regiões. Pagamento é COD (na entrega) ✅"
  payment_info:
    - "O link que envio é só pra confirmar endereço e acompanhar pelo WhatsApp. O pagamento é **na entrega** (COD)."
