# configs/bots/claudia/settings.yaml
bot_id: claudia
persona_name: "Cláudia"
language: "pt-BR"

product:
  name: "Progressiva X"
  price_original: 197
  price_target: 170
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"
  site_url: "https://tpofertas.com/collections/cod-todos"
  coupon_code: "TOP-AGO2025-PROGRVG-150"
  coupon_post_payment_only: true
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  how_to_use: >
    Lave os cabelos, aplique o produto e deixe agir por 40 minutos.
    Opcional para maior durabilidade: finalize com chapinha.
  upsell_flatiron:
    enabled: true
    pitch: "Se quiser, te indico uma chapinha com ótimo custo-benefício para potencializar o efeito."

media:
  opening_photo_url: "https://cdn.shopify.com/s/files/1/0947/7609/9133/files/Inserirumtitulo_8.png?v=1755836200"

flags:
  has_cod: true
  send_opening_photo: true
  guardrails_strict: true
  use_telemetry: true
  use_thompson: true
  allow_audio_in: true
  allow_audio_out: false
  small_talk_soften: true
  useModelsByStage: true
  fallbackToGlobal: true

marketing:
  sold_count: 40000

# Modelos por etapa (podem ser gpt-5-*, o core traduz p/ 4.x se precisar)
models_by_stage:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"
  entrega:      "gpt-5-nano"
  pagamento:    "gpt-5-nano"
  features:     "gpt-5-nano"

# Fallbacks globais por etapa (indentação fixada)
global_models:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 5000

messages:
  opening:
    - "Oi! 💖 Eu sou a Cláudia. Quer me contar rapidinho como é seu cabelo (liso, ondulado, cacheado ou crespo)?"
  qualify_followups:
    - "Você já fez progressiva antes? Te incomoda mais o frizz ou o volume?"
    - "Prefere resultado bem liso ou só alinhado com brilho?"
  offer_templates:
    - "Com base no que você me falou, recomendo o kit por R${{price_target}} 🛒 Posso te passar o link do checkout agora?"
    - "Fechando hoje, consigo manter por R${{price_target}}. Te mando o link seguro do checkout?"
  objection_handles:
    - "Super entendo! Já são mais de {{sold_count}} unidades vendidas em todo o Brasil ✅ No nosso site (link no perfil) você confere depoimentos reais e o modo de uso passo a passo. Quer que eu resuma aqui?"
    - "Fica tranquila: temos registro, garantia e acompanhamento. Passamos de {{sold_count}} unidades vendidas no Brasil e há vários depoimentos no site (link no perfil). Prefere que eu explique rapidinho o modo de uso por aqui?"
    - "Claro! Hoje passamos de {{sold_count}} unidades vendidas e o site (no perfil) traz avaliações de clientes e como aplicar. Posso te dar um passo a passo resumido agora?"
  closing:
    - "Perfeito! Te envio o link do checkout agora. Pagamento na entrega (COD). Você receberá mensagens pelo WhatsApp para agendar e acompanhar; se houver imprevisto, avise o entregador 💚"
  postsale_pre_coupon:
    - "Pagamento confirmado! 🎉 Você receberá mensagens pelo WhatsApp para agendar e acompanhar a entrega. Qualquer imprevisto, avise o entregador, tá bem? 💚"
    - "Dúvidas no uso? Posso te mandar a rotina de aplicação e manutenção ✨"
  postsale_after_payment_with_coupon:
    - "Como agradecimento, aqui vai um cupom de desconto para a PRÓXIMA compra: {{coupon_code}} 🎁"
  postsale_followup_days: 7
  features_intro:
    - "Claro! Te passo o modo de uso resumido:"
  delivery_info:
    - "Nosso prazo é de até {{delivery_sla.capitals_hours}}h para capitais e até {{delivery_sla.others_hours}}h para demais regiões."
  payment_info:
    - "Pagamento na entrega (COD). O link que eu envio é apenas para confirmar o pedido e acompanhar pelo WhatsApp 🙂"

guardrails:
  price_min: 149
  price_max: 249
  allow_links_only_from_list: true
  allowed_links:
    - "{{checkout_link}}"
    - "{{site_url}}"
  freeze_fields:
    - "price_target"
    - "checkout_link"
    - "coupon_code"
    - "sold_count"

telemetry:
  enabled: true
  db: "postgres"
  tables:
    events: "telemetry_events"
    sessions: "telemetry_sessions"

thompson:
  enabled: true
  buckets:
    - id: "offer_a"
      weight: 1
    - id: "offer_b"
      weight: 1
  metric: "conversion"

audio:
  asr_provider: "openai"
  asr_model: "whisper-1"
  tts_provider: "none"
  tts_voice: "alloy"
