bot_id: claudia

flags:
  flow_only: true              # respostas só dos flows/orquestrador
  debug_trace_replies: true    # carimbo (flow/...)
  has_cod: true
  force_funnel: true           # dica pro app: priorizar o funil determinístico

company:
  name: "TopOfertas"
  hours: "06:00–21:00"

product:
  name: "Progressiva Vegetal"
  price_original: 197
  price_target: 170
  applications_up_to: 10
  duration_avg: "de 2 a 3 meses"
  volume_ml: 500
  site_url: "https://seusite.com"
  checkout_link: "https://seusite.com/checkout"
  refund_days_after_delivery: 7
  how_to_use: "Lave os cabelos, seque 80%, aplique mecha a mecha, pause 40–50min, enxágue, escove e pranche."
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  coupon_post_payment_only: false
  coupon_code: ""

media:
  # Usada pelo orquestrador para enviar AUTOMATICAMENTE 1x na etapa greet
  opening_photo_url: "https://cdn.seusite.com/arte-abertura.jpg"

guardrails:
  # O orquestrador só deixa links da lista abaixo passarem “integros”
  allow_links_only_from_list: true
  allowed_links:
    - "{{product.site_url}}"
    - "{{product.checkout_link}}"
  # Limites de preço pra prevenir vazamento de valores errados
  price_min: 100
  price_max: 300

messages:
  opening:
    - "Oi, amor! 💖 Eu sou a Cláudia. Posso te explicar rapidinho sobre a *Progressiva Vegetal*?"
  postsale_pre_coupon:
    - "Pedido confirmado! Vou te enviar por aqui o status e o passo a passo de uso."
  postsale_after_payment_with_coupon:
    - "Obrigada pela compra! Usa o cupom **{{coupon_code}}** na próxima."
  delivery_info:
    - "Entregamos rápido: **{{delivery_sla.capitals_hours}}h** capitais / **{{delivery_sla.others_hours}}h** demais locais."
  features_intro:
    - "Como usar (resumo):"

# (Opcional) promoções — você pode ligar isso quando quiser
promotions:
  raffle:
    enabled: false
    teaser: "Comprando este mês você participa do nosso sorteio. Quer saber como funciona?"
