bot_id: claudia
persona_name: "Cláudia"
language: "pt-BR"

product:
  name: "Progressiva X"
  price_original: 197
  price_target: 170
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"
  coupon_code: "TOP-AGO2025-PROGRVG-150"
  has_cod: true

flags:
  has_cod: true
  send_opening_photo: true             # envia foto de abertura (se existir no flow)
  guardrails_strict: true              # regras rígidas (não inventar preço/link)
  use_telemetry: true                  # envia eventos para Postgres (CoNexus)
  use_thompson: true                   # Thompson/AB para oferta
  allow_audio_in: true                 # cliente pode enviar áudio
  allow_audio_out: false               # TTS depois
  small_talk_soften: true              # tom leve e vendedor

# ⚠️ Padronizei nomes SEM acento para casar com intents/flows
models_by_stage:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5-full"
  fechamento:   "gpt-5-mini"
  posvenda:     "gpt-5-nano"

typing:
  ms_per_char: 35
  min_ms: 800
  max_ms: 5000

messages:
  opening:
    - "Oi! 💖 Eu sou a Cláudia. Quer me contar rapidinho como é seu cabelo (liso, ondulado, cacheado ou crespo)?"
  qualify_followups:
    - "Você já fez progressiva antes? Te incomoda mais o frizz ou o volume?"
    - "Prefere resultado bem liso ou só alinhado com brilho?"
  offer_templates:
    - "Com base no que você me falou, recomendo o kit por R${{price_target}} 🛒 Posso te passar o link do checkout agora?"
    - "Tenho cupom {{coupon_code}} que reduz para R${{price_target}}. Quer aproveitar?"
  objection_handles:
    - "Te entendo! É sem formol, com registro e garantia. Posso te mostrar resultados reais e o modo de uso?"
    - "Se não amar o resultado, a gente orienta até acertar. Quer ver o passo a passo simples?"
  closing:
    - "Perfeito! Te mando o link do checkout agora? Assim já garante o valor com o cupom 😉"
  postsale:
    - "Qualquer dúvida no uso me chama aqui, combinado? Posso te mandar uma rotina de manutenção ✨"

guardrails:
  price_min: 149
  price_max: 249
  allow_links_only_from_list: true
  allowed_links:
    - "{{checkout_link}}"
  freeze_fields:
    - "price_target"
    - "checkout_link"
    - "coupon_code"

telemetry:
  enabled: true
  db: "postgres"               # CoNexus
  tables:
    events: "telemetry_events"
    sessions: "telemetry_sessions"

thompson:
  enabled: true
  buckets:
    - id: "offer_a"
      weight: 1
    - id: "offer_b"
      weight: 1
  metric: "conversion"

audio:
  asr_provider: "openai"
  asr_model: "whisper-1"
  tts_provider: "none"
  tts_voice: "alloy"
