# configs/bots/claudia/settings.yaml
bot_id: claudia
persona_name: "Cláudia"
language: "pt-BR"

company_name: "TopOfertas"

business:
  tz_offset_hours: -3          # BRT
  hours_start: "06:00"
  hours_end: "21:00"

marketing:
  sold_count: 40000

sweepstakes:
  enabled: true
  prizes:
    - "1º: Escova/Chapinha Alisadora 3 em 1"
    - "2º: 1 Progressiva Vegetal"
    - "3º: Ativador Capilar"
  messages:
    teaser:
      - "Ah! Todo mês rola um sorteio ✨ 1º Escova Alisadora 3 em 1, 2º uma Progressiva Vegetal e 3º um Ativador Capilar. Você já está participando ao comprar 😉"

product:
  name: "Progressiva Vegetal"
  price_original: 197
  price_target: 170
  volume_ml: 500
  applications_range: "até 10 aplicações"
  duration_avg: "em média 3 meses"
  checkout_link: "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"  # fallback
  site_url: "https://tpofertas.com/collections/cod-todos"
  coupon_code: ""
  coupon_post_payment_only: true
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  how_to_use: >
    Lave os cabelos, aplique o produto e deixe agir por ~40 minutos. Para maior durabilidade, finalize com prancha/escova (opcional).

flags:
  has_cod: true
  send_opening_photo: false            # evitar foto com CTA precoce
  guardrails_strict: true
  use_telemetry: true
  allow_audio_in: true
  allow_audio_out: false
  small_talk_soften: true
  useModelsByStage: true
  fallbackToGlobal: true
  checkout_mode: "concierge"           # "link" | "concierge" | "hybrid"

payments:
  installments:
    enabled: true
    max_installments: 12
    hint_text: "até 12x"

media:
  opening_photo_url: ""                # opcional

guardrails:
  allow_links_only_from_list: true
  allowed_links:
    - "https://entrega.logzz.com.br/pay/memmpxgmg/progcreme170"
    - "https://entrega.logzz.com.br"
    - "https://tpofertas.com/collections/cod-todos"

messages:
  opening:
    - "Oi, amor! 💖 Eu sou a Cláudia. Me conta rapidinho como é seu cabelo (liso, ondulado, cacheado ou crespo)?"
  postsale_pre_coupon:
    - "Compra confirmada! ✨ Se precisar de ajuda com a aplicação, tô aqui. E você já está concorrendo aos prêmios do mês 🎁"
  postsale_after_payment_with_coupon:
    - "Obrigada pela confiança! Anota seu cupom para próxima compra: {{coupon_code}} 🥰"

# Modelos por estágio — pode manter 5.x (o core traduz p/ 4o/4o-mini se necessário)
models_by_stage:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"

global_models:
  recepcao:     "gpt-5-nano"
  qualificacao: "gpt-5-nano"
  oferta:       "gpt-5-mini"
  objecoes:     "gpt-5"
  fechamento:   "gpt-5"
  posvenda:     "gpt-5-nano"
