bot_id: claudia
flags:
  flow_only: true
  debug_trace_replies: true
  has_cod: true

company:
  name: "TopOfertas"
  hours: "06:00–21:00"

product:
  name: "Progressiva Vegetal"
  price_original: 197
  price_target: 170
  applications_up_to: 10
  duration_avg: "de 2 a 3 meses"
  volume_ml: 500
  site_url: "https://seusite.com"
  checkout_link: "https://seusite.com/checkout"
  refund_days_after_delivery: 7
  how_to_use: "Lave os cabelos, seque 80%, aplique mecha a mecha, pause 40–50min, enxágue, escove e pranche."
  delivery_sla:
    capitals_hours: 24
    others_hours: 72
  coupon_post_payment_only: false
  coupon_code: ""

media:
  opening_photo_url: "https://cdn.seusite.com/arte-abertura.jpg"

guardrails:
  allowed_links:
    - "https://seusite.com"
    - "https://seusite.com/checkout"

messages:
  opening:
    - "Oi, amor! 💖 Eu sou a Cláudia. Posso te explicar rapidinho sobre a *Progressiva Vegetal*?"
  postsale_pre_coupon:
    - "Pedido confirmado! Vou te enviar por aqui o status e o passo a passo de uso."
  postsale_after_payment_with_coupon:
    - "Obrigada pela compra! Usa o cupom **{{coupon_code}}** na próxima."
  delivery_info:
    - "Entregamos rápido: **{{delivery_sla.capitals_hours}}h** capitais / **{{delivery_sla.others_hours}}h** demais locais."
  features_intro:
    - "Como usar (resumo):"
