# configs/bots/claudia/claudia.flow.yml
# Funil determinístico com carimbos (flow/...) e rotas claras.

version: 1
bot_id: claudia

stages:
  greet:
    entry:
      - kind: call
        fn: "greet"          # configs/bots/claudia/flow/greet.js
    on_intent:
      offer:        "offer"
      close:        "close"
      postsale:     "postsale"
      default:      "qualify"

  qualify:
    entry:
      - kind: call
        fn: "qualify"        # configs/bots/claudia/flow/qualify.js (anti-loop + 'pular')
    on_intent:
      offer:        "offer"   # "quanto custa" → oferta
      close:        "close"   # "link/checkout" → fechamento
      jump:         "offer"   # "pular" → avança
      objection:    "offer"   # trata e leva para oferta
      delivery:     "offer"   # responde via FAQ interno e empurra oferta
      payment:      "offer"
      features:     "offer"
      default:      "qualify"

  offer:
    entry:
      - kind: call
        fn: "offer"          # configs/bots/claudia/flow/offer.js (preço + CTA link)
    on_intent:
      close:        "close"
      postsale:     "postsale"
      default:      "close"

  close:
    entry:
      - kind: call
        fn: "close"          # configs/bots/claudia/flow/close.js (stickiness)
    on_intent:
      confirm:      "postsale" # “confirmo” → confirmação
      postsale:     "postsale"
      # stickiness: permanecer em close salvo cancelamento explícito
      default:      "close"

  postsale:
    entry:
      - kind: call
        fn: "postsale"       # configs/bots/claudia/flow/postsale.js
    on_intent:
      default:      "postsale"

carimbos:
  enabled: true
  pattern: "(flow/{{stage}})"   # todos os flows já retornam reply com carimbo

guardrails:
  links:
    whitelist:
      - "{{product.site_url}}"
      - "{{product.checkout_link}}"
  price:
    min: 100
    max: 300
    show_only_when_intent: ["offer"]

media:
  opening_photo:
    enabled: true
    source: "{{media.opening_photo_url}}"
    stage: "greet"             # disparo 1x por sessão

notes:
  - "Este YAML só roteia. O conteúdo das respostas fica nos flows JS e no funnel.js."
