# configs/docs/conexus/bots/claudia.flow.v1.yaml
version: 1
bot_id: claudia

stages:
  greet:
    entry:
      - kind: call
        fn: "greet"
    on_intent:
      offer:        "offer"
      close:        "close"
      postsale:     "postsale"
      default:      "qualify"

  qualify:
    entry:
      - kind: call
        fn: "qualify"
    on_intent:
      offer:        "offer"
      close:        "close"
      objection:    "offer"
      delivery:     "offer"
      payment:      "offer"
      features:     "offer"
      default:      "offer"

  offer:
    entry:
      - kind: call
        fn: "offer"
    on_intent:
      close:        "close"
      postsale:     "postsale"
      default:      "close"

  close:
    entry:
      - kind: call
        fn: "close"
    on_intent:
      confirm:      "postsale"
      postsale:     "postsale"
      default:      "close"

  postsale:
    entry:
      - kind: call
        fn: "postsale"
    on_intent:
      default:      "postsale"

carimbos:
  enabled: true
  pattern: "(flow/{{stage}})"

guardrails:
  links:
    whitelist:
      - "{{product.site_url}}"
      - "{{product.checkout_link}}"
  price:
    min: 100
    max: 300
    show_only_when_intent: ["offer"]

media:
  opening_photo:
    enabled: true
    source: "{{media.opening_photo_url}}"
    stage: "greet"

notes:
  - "YAML de roteamento/telemetria. Respostas ficam nos flows JS."
