version: 1.0
kind: conexus_flow
bot_id: "claudia"
flow_id: "default"
title: "Funil Padrão - Cláudia"
currency: "BRL"

price_target: "{{settings.product.price_target}}"
checkout_link: "{{settings.product.checkout_link}}"
site_url: "{{settings.product.site_url}}"

stages:
  - stage_id: recepcao
    intents_in: ["greet","recepcao","start","hello","oi","bom dia","boa tarde","boa noite"]
    goals:
      - "Identificar tipo de cabelo (liso/ondulado/cacheado/crespo)"
      - "Coletar uma dor principal (frizz/volume)"
    required_actions: ["ask_hair_type"]
    guardrails:
      allowed_links: []
    kpis:
      - { id: "tffr", metric: "time_to_first_reply", target: 5 }
      - { id: "stage_completion", metric: "stage_completion_rate", target: 85 }
    exit_conditions:
      - "Tipo de cabelo identificado"
    sla_sec: 60

  - stage_id: qualificacao
    intents_in: ["qualificacao","qualify"]
    goals:
      - "Entender histórico (já fez progressiva?) e resultado desejado"
    required_actions: []
    guardrails: {}
    kpis:
      - { id: "msgs_to_offer", metric: "messages_to_offer", target: 4 }
    exit_conditions:
      - "Pronto para apresentar preço"
    sla_sec: 120

  - stage_id: oferta
    intents_in: ["oferta","offer","preco","preço","qual o preço","valor","quanto custa"]
    goals:
      - "Informar preço-alvo e oferecer link de checkout"
    required_actions: ["send_price","send_link"]
    guardrails:
      price_min: 149
      price_max: 249
      allowed_links:
        - "{{settings.product.checkout_link}}"
        - "{{settings.product.site_url}}"
    kpis:
      - { id: "price_rate", metric: "price_disclosed_rate", target: 95 }
      - { id: "link_rate",  metric: "link_sent_rate",      target: 95 }
    exit_conditions:
      - "Cliente recebeu preço e link"
    sla_sec: 120

  - stage_id: objecoes
    intents_in: ["objection","objecoes","negociacao"]
    goals:
      - "Tratar preço/parcelas/segurança e manter interesse"
    required_actions: []
    guardrails: {}
    kpis:
      - { id: "recover_to_close", metric: "bounce_to_close_rate", target: 50 }
    exit_conditions:
      - "Remover objeção ou redirecionar para fechamento"
    sla_sec: 180

  - stage_id: fechamento
    intents_in: ["fechamento","close","checkout","finalizar","comprar","pedido","carrinho","link"]
    goals:
      - "Confirmar dados de entrega e gerar pedido COD"
    required_actions: ["collect_address","confirm_consent"]
    guardrails:
      allowed_links:
        - "{{settings.product.checkout_link}}"
    kpis:
      - { id: "address_completion", metric: "address_completion_rate", target: 80 }
    exit_conditions:
      - "Dados confirmados (consent_checkout=true)"
    sla_sec: 300

  - stage_id: posvenda
    intents_in: ["posvenda","postsale","pós-venda"]
    goals:
      - "Enviar resumo, cupom pós-pagamento e instruções de uso"
    required_actions: ["send_howto","send_delivery_sla"]
    guardrails:
      allowed_links:
        - "{{settings.product.site_url}}"
    kpis:
      - { id: "howto_sent", metric: "howto_delivery_rate", target: 95 }
    exit_conditions:
      - "Cliente recebeu instruções e canais de suporte"
    sla_sec: 180
