version: 1.0
kind: conexus_flow
bot_id: "maria"
flow_id: "default"
title: "Funil Padrão - Maria"
currency: "BRL"
price_target: "{{settings.product.price_target}}"
checkout_link: "{{settings.product.checkout_link}}"
site_url: "{{settings.product.site_url}}"

stages:
  - stage_id: recepcao
    intents_in: ["greet", "recepcao", "start", "hello", "oi", "bom dia", "boa tarde", "boa noite"]
    goals:
      - "Identificar tipo de cabelo (liso/ondulado/cacheado/crespo)"
      - "Coletar 1 dor principal (frizz/volume)"
    required_actions: ["ask_hair_type"]
    guardrails: { allowed_links: [] }
    kpis:
      - { id: "tffr", metric: "time_to_first_reply", target: 5 }
      - { id: "stage_completion", metric: "stage_completion_rate", target: 85 }
    exit_conditions: ["Tipo de cabelo identificado"]
    sla_sec: 60

  - stage_id: qualificacao
    intents_in: ["qualificacao", "qualify"]
    goals: ["Histórico e resultado desejado"]
    required_actions: []
    guardrails: {}
    kpis:
      - { id: "msgs_to_offer", metric: "messages_to_offer", target: 4 }
    exit_conditions: ["Pronto para apresentar preço"]
    sla_sec: 120

  - stage_id: oferta
    intents_in: ["oferta", "offer", "preco", "preço", "qual o preço", "valor", "quanto custa"]
    goals: ["Informar preço-alvo e oferecer link de checkout"]
    required_actions: ["send_price", "send_link"]
    guardrails:
      price_min: 149
      price_max: 249
      allowed_links:
        - "{{settings.product.checkout_link}}"
        - "{{settings.product.site_url}}"
    kpis:
      - { id: "price_rate", metric: "price_disclosed_rate", target: 95 }
      - { id: "link_rate",  metric: "link_sent_rate",      target: 85 }
    exit_conditions: ["Link enviado ao cliente"]
    sla_sec: 90

  - stage_id: objecoes
    intents_in: ["objecoes", "objeções", "tem formol", "cheiro forte", "entrega", "prazo", "seguro", "composição"]
    goals: ["Sanar objeção e manter oferta viva"]
    required_actions: ["handle_objection"]
    guardrails: {}
    kpis:
      - { id: "objection_ok", metric: "objection_resolution_rate", target: 70 }
    exit_conditions: ["Cliente retorna ao fluxo de oferta/fechamento"]
    sla_sec: 120

  - stage_id: fechamento
    intents_in: ["fechamento", "checkout", "comprar", "finalizar", "fechar pedido"]
    goals: ["Confirmar COD e link seguro"]
    required_actions: ["confirm_cod"]
    guardrails:
      allowed_links:
        - "{{settings.product.checkout_link}}"
    kpis:
      - { id: "link_rate_close", metric: "link_sent_rate", target: 95 }
    exit_conditions: ["Cliente recebe link e confirma intenção de compra"]
    sla_sec: 120

  - stage_id: posvenda
    intents_in: ["posvenda", "pós-venda", "payment_ok"]
    goals: ["Agradecer pagamento e confirmar envio"]
    required_actions: ["confirm_payment"]
    guardrails: {}
    kpis:
      - { id: "stage_completion_pos", metric: "stage_completion_rate", target: 95 }
    exit_conditions: ["Mensagem de confirmação enviada"]
    sla_sec: 300
